CREATE TABLE IF NOT EXISTS survey_responses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  coop_id INT NULL COMMENT 'Logical reference to active_coop.c_id',
  coop_name VARCHAR(255) NOT NULL COMMENT 'Cooperative name snapshot at submission time',
  coop_type VARCHAR(100) NOT NULL,
  member_range VARCHAR(50) NULL,
  staff_range VARCHAR(50) NULL,
  respondent_role VARCHAR(100) NULL,
  current_tools LONGTEXT NULL COMMENT 'JSON array',
  tech_level TINYINT UNSIGNED NOT NULL,
  data_storage LONGTEXT NULL COMMENT 'JSON array',
  time_consuming_jobs LONGTEXT NULL COMMENT 'JSON array',
  current_problems LONGTEXT NULL COMMENT 'JSON array',
  most_time_job TEXT NULL,
  most_time_job_detail TEXT NULL,
  desired_technology_jobs LONGTEXT NULL COMMENT 'JSON array',
  desired_system_features LONGTEXT NULL COMMENT 'JSON array',
  ai_interest VARCHAR(50) NOT NULL,
  desired_ai_jobs LONGTEXT NULL COMMENT 'JSON array',
  ai_priority TEXT NULL,
  shared_system_opinion VARCHAR(50) NULL,
  shareable_data LONGTEXT NULL COMMENT 'JSON array',
  shared_system_concerns LONGTEXT NULL COMMENT 'JSON array',
  computer_readiness VARCHAR(50) NULL,
  internet_readiness VARCHAR(50) NULL,
  staff_tech_skill VARCHAR(50) NULL,
  pilot_readiness VARCHAR(50) NOT NULL,
  support_needs LONGTEXT NULL COMMENT 'JSON array',
  support_formats LONGTEXT NULL COMMENT 'JSON array',
  first_priority_system TEXT NULL,
  priority_reason TEXT NULL,
  current_time_spent VARCHAR(100) NULL,
  expected_outcomes LONGTEXT NULL COMMENT 'JSON array',
  biggest_opportunity TEXT NULL,
  dream_system TEXT NULL,
  additional_suggestions TEXT NULL,
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(500) NULL,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_survey_coop_id (coop_id),
  KEY idx_survey_submitted_at (submitted_at),
  KEY idx_survey_coop_type (coop_type),
  KEY idx_survey_tech_level (tech_level),
  KEY idx_survey_ai_interest (ai_interest),
  KEY idx_survey_pilot_readiness (pilot_readiness)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
